add parastell tool, overhaul text wrapping, allow more generalized text in plot
svalinn/radial_build_tools pull request #11
Opened 2024-04-26 22:54 UTC by Edgar-21

**plot_parastell_build.py**
plot_parastell_build takes a parastell build dict, and phi and theta value, along with the usual plot_radial_build inputs and extracts/formats the data how plot_radial_build likes it, then calls plot_radial_build to make the image and yml file.

**plot_radial_build.py**
Speaking of, plot_radial_build can now write the yml representation of the plot, and does so by default, along with the usual png.

Additionally, I overhauled how text gets formatted and put into the rectangles, to allow for more flexibility and introduced a 'description' element to the layer dict that allows arbitrary text to be added to each rectangle.

Each layer in the plot_radial_build dict can now have any combination of the three keys, and can also be empty.

**General Updates**
I added a couple examples as well and updated the readme to indicate they exist, and describe calling plot_radial_build from the command line

**Demonstration**
Here is the plot generated by the example 
![image](https://github.com/svalinn/radial_build_tools/assets/84034227/025e5d2d-9c33-41b4-a01e-704fbd063287)
And here is the plot generated by the parastell tool example
![image](https://github.com/svalinn/radial_build_tools/assets/84034227/f05437b5-7b0d-458e-a6a9-bb892a73b9f9)

closes #10
closes #8 (not notebooks, but I can change that if desired)

2024-04-28 19:30 UTC, gonuke requested changes
One high-level design suggestion

2024-04-28 19:30 UTC, gonuke commented on plot_parastell_build.py
What if instead of a different script, this just had a method that extracted a radial build from a parastell build, and then the normal plot_radial_build script could be used?

We shouldn't need to worry about all the plot details in a method that is basically just interpreting a parastell radial build. (separation of concerns)

2024-05-10 20:30 UTC, Edgar-21 commented on plot_parastell_build.py
Maybe went a little over top here, but I combined the functions in `plot_radial_build.py` into a class, and added a method that interprets parastell builds rather than have a separate script as you suggested. Updated the examples to reflect this change as well. I imagine in the future perhaps the radial build class can be more of its own thing if additional functionality is desired, and just have a method for plotting, rather than having plotting being the main purpose of the class. Sorry for the big diff, almost everything is the same just moved around a bit for use in the class

2024-05-12 22:40 UTC, Edgar-21 commented
superseded by #13

2024-05-12 22:40 UTC, closed without merging