Mix HCPB Materials using fusion-materials-db
svalinn/radial_build_tools pull request #26
Opened 2024-11-05 21:47 UTC by anu1217

fixes #18, #21

2024-11-22 00:27 UTC, anu1217 commented
> I think that @katielygre has proposed one or two more layers of subdirectory for these examples in #27 - I think it would be good to match her approach.

Yes, we decided today to have multiple subdirectories for our examples, but we were a little concerned that making the same subdirectories within separate PRs might lead to a merge conflict. If that's not the case I'll go ahead and match the structure in #27.

2024-11-22 02:05 UTC, gonuke commented
Git only really cares about files for merge conflicts, so both making directories should be fine.

2025-01-14 02:26 UTC, Edgar-21 commented on examples/hcpb_radial_build_example/HCPB_Mix_Materials.py
> +mixmat_lib.write_json("mixedPureFusionMatsHCPB_libv1.json")
```suggestion
mixmat_lib.write_openmc("mixedPureFusionMatsHCPB_libv1.xml")
```
Then when you need to use it with OpenMC you can initialize the materials object from the xml

2025-01-14 02:26 UTC, Edgar-21 commented on examples/hcpb_radial_build_example/HCPB_Build_Dict.py
> +with open('mixedPureFusionMatsHCPB_libv1.json', 'r') as mixed_mat_json:
With the change to write to xml instead of json, you should be able to just initialize the openmc Materials object with that

2025-01-14 02:26 UTC, Edgar-21 commented on examples/hcpb_radial_build_example/HCPB_Build_Dict.py
> +        #"composition": mixed_materials["FWWArmor"]["vol_fracs"],
we could fix these commented out lines to refer to your material dictionary to tie it all together.

2025-01-15 18:27 UTC, gonuke requested changes
A couple of minor points... nearly finished with this

2025-01-15 18:27 UTC, gonuke commented on examples/hcpb_radial_build_example/HCPB_Build_Dict.py
> +        return yaml_inputs
These functions can be defined outside of `main` at the global scope.  I'm not sure I have a clear reason for this other than reduced complexity.  I think it is rare to have functions defined within other functions, and usually serves a very specific purpose.

2025-01-15 18:27 UTC, gonuke commented on examples/hcpb_radial_build_example/HCPB_Build_Dict.py
> +    plot_radial_build(yaml_inputs['filenames']['radial_plot_name'], build_dict)
Perhaps this can be an option governed by something in argparse

2025-01-15 18:27 UTC, gonuke commented on examples/hcpb_radial_build_example/HCPB_Build_Dict.py
> +    "sol": {
Probably makes sense to indent all of these once

2025-01-16 03:25 UTC, gonuke approved these changes
This looks good to me - thanks for pulling this all together.

2025-01-16 21:16 UTC, merged