Added DCLL and HCPB example folder and DCLL example files
svalinn/radial_build_tools pull request #27
Opened 2024-11-21 21:21 UTC by katielygre

Added file structure, examples, and documentation for using radial build tools and fusion materials database. There is a single README because the workflow is similar in both examples.

2024-11-22 16:57 UTC, gonuke requested changes
Thanks for getting this launched @katielygre ! - There's a lot of little things here - happy to discuss in person

2024-11-22 16:57 UTC, gonuke commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_materials.py
> +}
Alternatively:
```
material_dict['sol'] = {
    "composition" : {
        "Void" : 1.0
    }, 
    "citation" : "DavisFusEngDes_2018"
}
```

2024-11-22 16:57 UTC, gonuke commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_materials.py
> +for material, value in material_dict.items():
```suggestion
for mat_name, mat_data in material_dict.items():
```

2024-11-22 21:48 UTC, gonuke commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_json_to_openmc.py
> +def makematerial(material_json,path_to_cross_sections):
Be sure to add a docstring that describes what this function does

2025-01-11 23:00 UTC, gonuke requested changes
This is coming along nicely @katielygre - I left a few comments here that we can discuss more next week.

2025-01-14 18:57 UTC, lewisgross1296 reviewed
Let me know your thoughts about setting cross sections. It could be that my understanding of specifying cross sections is not compatible with your vision for how this will be used.

2025-01-14 18:57 UTC, lewisgross1296 commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_radial_build.py
> +    materials.cross_sections=path_to_cross_sections
Is there a reason you aren't using the `OPENMC_CROSS_SECTIONS` environment variable? If you truly want to set the path using this method to allow for more control for future users, would an `xs_path` command-line argument work as opposed to hard-coding the path?

2025-01-14 18:57 UTC, lewisgross1296 commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_json_to_openmc.py
> +def makematerial(material_json, path_to_cross_sections):
looks like it's an argument here. perhaps the main function could parse this from the command line if you don't want to use the env var way?

2025-01-14 19:30 UTC, katielygre commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_json_to_openmc.py
> +def makematerial(material_json, path_to_cross_sections):
this file is getting removed

2025-01-15 18:52 UTC, gonuke requested changes
a few final changes

2025-01-15 18:52 UTC, gonuke commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_radial_build.py
> +    plot_dcll_radial_build(build_dict)
This could be an option governed by a user command-line argument (see `argparse`)

2025-01-15 18:52 UTC, gonuke commented on examples/dcll_hcpb_examples/README.md
I think this needs to be updated to match what actually happens now

2025-01-15 20:07 UTC, anu1217 commented on examples/dcll_hcpb_examples/README.md
> +    adding `"density_factor"` when needed
```suggestion
    adding `density_factor` when needed
```

2025-01-15 20:13 UTC, anu1217 commented on examples/dcll_hcpb_examples/README.md
> +        2. Uses the `material_db_tools` `mix_by_volume` to create a PyNE material library
```suggestion
        a) Opens [`PureFusionMaterials_libv1.json`](https://github.com/svalinn/fusion-material-db/blob/main/db-outputs/PureFusionMaterials_libv1.json) 
        
        b) Calls `mix_by_volume()` from `material_db_tools` ([fusion-material-db](https://github.com/svalinn/fusion-material-db/blob/main/material-db-tools/material_db_tools.py)) to create a PyNE material library
```

2025-01-15 20:17 UTC, anu1217 commented on examples/dcll_hcpb_examples/README.md
> +    4. Create a function to call the others and export the materials library to XML file
```suggestion
    4. Create a `main()` function to call helper functions and export the materials library to XML file
```

2025-01-15 20:20 UTC, anu1217 commented on examples/dcll_hcpb_examples/README.md
> +    2. Import function created earlier to make materials dictionary
```suggestion
    2. Import the function created in 3) to make materials dictionary
```

2025-01-15 20:21 UTC, anu1217 commented on examples/dcll_hcpb_examples/README.md
> +    5. Create a function that does the following
```suggestion
    5. Create a `main()` function that does the following:
```

2025-01-16 03:28 UTC, gonuke requested changes
I think your argparse variable could be called `plot` instead of `process`

2025-01-16 03:28 UTC, gonuke commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_radial_build.py
> +    parser.add_argument('-p','--process', action='store_true', help="Call the plotting function if this flag is provided.")
```suggestion
    parser.add_argument('-p','--plot', action='store_true', help="Call the plotting function if this flag is provided.")
```

2025-01-16 03:28 UTC, gonuke commented on examples/dcll_hcpb_examples/dcll_radial_build_example/dcll_radial_build.py
> +    if args.process:
Assuming the above change of this variable name in argparse
```suggestion
    if args.plot:
```

2025-01-16 15:15 UTC, gonuke approved these changes

2025-01-16 15:15 UTC, merged